package com.example.domain.model

enum class ModelCategory {
    ULTRA_FAST, // < 1GB
    BALANCED,   // 1GB - 1.5GB
    HIGH_QUALITY // > 1.5GB
}

data class AiModelInfo(
    val id: String,
    val name: String,
    val developer: String,
    val sizeBytes: Long,
    val sizeFormatted: String,
    val ramRequiredMb: Int,
    val parameterCount: String,
    val quantization: String,
    val targetTokensPerSec: Double, // Baseline t/s on 4-thread mobile CPU
    val description: String,
    val tags: List<String>,
    val category: ModelCategory,
    val isRecommended: Boolean = false,
    val downloadUrl: String
) {
    companion object {
        val CATALOG = listOf(
            AiModelInfo(
                id = "qwen-2.5-0.5b-int4",
                name = "Qwen 2.5 0.5B",
                developer = "Alibaba Cloud",
                sizeBytes = 368_000_000L,
                sizeFormatted = "368 MB",
                ramRequiredMb = 650,
                parameterCount = "0.49 Billion",
                quantization = "INT4 (q4_k_m)",
                targetTokensPerSec = 28.5,
                description = "Ultra-fast micro model designed for instant mobile CPU inference. Exceptional math, logic, and multi-language support.",
                tags = listOf("Ultra Fast", "Math", "Multi-lingual", "Low Memory"),
                category = ModelCategory.ULTRA_FAST,
                isRecommended = true,
                downloadUrl = "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf"
            ),
            AiModelInfo(
                id = "gemma-2-2b-int4",
                name = "Google Gemma 2 2B",
                developer = "Google DeepMind",
                sizeBytes = 1_380_000_000L,
                sizeFormatted = "1.38 GB",
                ramRequiredMb = 1800,
                parameterCount = "2.6 Billion",
                quantization = "INT4 (q4_k_m)",
                targetTokensPerSec = 14.2,
                description = "State-of-the-art small open model built by Google using Gemini research. Superior reasoning, world knowledge, and natural dialogue.",
                tags = listOf("Google", "High Accuracy", "General Knowledge", "Reasoning"),
                category = ModelCategory.BALANCED,
                isRecommended = true,
                downloadUrl = "https://huggingface.co/google/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q4_K_M.gguf"
            ),
            AiModelInfo(
                id = "minicpm-2b-int4",
                name = "MiniCPM 2B",
                developer = "OpenBMB / Tsinghua",
                sizeBytes = 1_210_000_000L,
                sizeFormatted = "1.21 GB",
                ramRequiredMb = 1600,
                parameterCount = "2.4 Billion",
                quantization = "INT4 (q4_k_m)",
                targetTokensPerSec = 16.8,
                description = "End-to-end optimized for mobile CPU execution with performance matching 7B models on code generation and logical reasoning.",
                tags = listOf("OpenBMB", "Mobile First", "Code", "Instruction-Tuned"),
                category = ModelCategory.BALANCED,
                isRecommended = true,
                downloadUrl = "https://huggingface.co/openbmb/MiniCPM-2B-sft-bf16-gguf/resolve/main/MiniCPM-2B-sft-q4_k_m.gguf"
            ),
            AiModelInfo(
                id = "minicpm-3-4b-int4",
                name = "MiniCPM 3.0 4B",
                developer = "OpenBMB / Tsinghua",
                sizeBytes = 2_100_000_000L,
                sizeFormatted = "2.10 GB",
                ramRequiredMb = 2900,
                parameterCount = "4.0 Billion",
                quantization = "INT4 (q4_k_m)",
                targetTokensPerSec = 11.5,
                description = "OpenBMB's premier 4B model rivaling GPT-3.5-Turbo performance. Outstanding multi-lingual writing, deep reasoning, and tool call generation.",
                tags = listOf("OpenBMB", "MiniCPM 3", "High Accuracy", "Writing", "Reasoning"),
                category = ModelCategory.HIGH_QUALITY,
                isRecommended = true,
                downloadUrl = "https://huggingface.co/openbmb/MiniCPM3-4B-GGUF/resolve/main/MiniCPM3-4B-Q4_K_M.gguf"
            ),
            AiModelInfo(
                id = "minicpm-1.2b-int4",
                name = "MiniCPM 1.2B Micro",
                developer = "OpenBMB / Tsinghua",
                sizeBytes = 690_000_000L,
                sizeFormatted = "690 MB",
                ramRequiredMb = 980,
                parameterCount = "1.2 Billion",
                quantization = "INT4 (q4_k_m)",
                targetTokensPerSec = 24.5,
                description = "Ultra-lightweight MiniCPM variant engineered specifically for zero-lag CPU execution on entry-level Android hardware.",
                tags = listOf("OpenBMB", "Micro", "Ultra Fast", "Low Memory"),
                category = ModelCategory.ULTRA_FAST,
                isRecommended = false,
                downloadUrl = "https://huggingface.co/openbmb/MiniCPM-1B-GGUF/resolve/main/MiniCPM-1B-Q4_K_M.gguf"
            ),
            AiModelInfo(
                id = "llama-3.2-1b-int4",
                name = "Llama 3.2 1B",
                developer = "Meta AI",
                sizeBytes = 780_000_000L,
                sizeFormatted = "780 MB",
                ramRequiredMb = 1100,
                parameterCount = "1.2 Billion",
                quantization = "INT4 (q4_k_m)",
                targetTokensPerSec = 22.0,
                description = "Meta's official lightweight Llama 3.2 model fine-tuned for high efficiency, fast text summarization, and task execution.",
                tags = listOf("Meta", "Llama 3", "Summarization", "Fast"),
                category = ModelCategory.ULTRA_FAST,
                isRecommended = false,
                downloadUrl = "https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf"
            ),
            AiModelInfo(
                id = "qwen-2.5-1.5b-int4",
                name = "Qwen 2.5 1.5B",
                developer = "Alibaba Cloud",
                sizeBytes = 980_000_000L,
                sizeFormatted = "980 MB",
                ramRequiredMb = 1350,
                parameterCount = "1.54 Billion",
                quantization = "INT4 (q4_k_m)",
                targetTokensPerSec = 19.4,
                description = "The sweet spot for mobile CPU chatting. Great balance between size under 1GB and strong coding & instruction capabilities.",
                tags = listOf("Coding", "Math", "General"),
                category = ModelCategory.BALANCED,
                isRecommended = false,
                downloadUrl = "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q4_k_m.gguf"
            ),
            AiModelInfo(
                id = "tinyllama-1.1b-int4",
                name = "TinyLlama 1.1B",
                developer = "StatNLP / OpenSource",
                sizeBytes = 640_000_000L,
                sizeFormatted = "640 MB",
                ramRequiredMb = 900,
                parameterCount = "1.1 Billion",
                quantization = "INT4 (q4_k_m)",
                targetTokensPerSec = 25.0,
                description = "Compact 1.1B Llama architecture trained on 3 trillion tokens. Lightweight companion for casual offline conversations.",
                tags = listOf("Lightweight", "Chat", "Casual"),
                category = ModelCategory.ULTRA_FAST,
                isRecommended = false,
                downloadUrl = "https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"
            ),
            AiModelInfo(
                id = "mistral-7b-v0.3-int4",
                name = "Mistral 7B Instruct v0.3",
                developer = "Mistral AI",
                sizeBytes = 3_800_000_000L,
                sizeFormatted = "3.80 GB",
                ramRequiredMb = 4800,
                parameterCount = "7.2 Billion",
                quantization = "INT4 (q4_k_m)",
                targetTokensPerSec = 8.5,
                description = "Mistral AI's flagship 7B model with 32k context window. Powerful logic, instruction adherence, function calling, and multilingual capabilities.",
                tags = listOf("Mistral", "Flagship 7B", "High Quality", "Code & Logic"),
                category = ModelCategory.HIGH_QUALITY,
                isRecommended = true,
                downloadUrl = "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf"
            ),
            AiModelInfo(
                id = "qwen-2.5-coder-1.5b-int4",
                name = "Qwen 2.5 Coder 1.5B Flash",
                developer = "Alibaba Cloud",
                sizeBytes = 980_000_000L,
                sizeFormatted = "980 MB",
                ramRequiredMb = 1350,
                parameterCount = "1.54 Billion",
                quantization = "INT4 (q4_k_m)",
                targetTokensPerSec = 21.0,
                description = "Specialized coding LLM trained on 5.5T code tokens. Rapid mobile generation for Python, Kotlin, JavaScript, and SQL.",
                tags = listOf("Qwen Coder", "Flash", "Coding", "Fast"),
                category = ModelCategory.BALANCED,
                isRecommended = true,
                downloadUrl = "https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF/resolve/main/qwen2.5-coder-1.5b-instruct-q4_k_m.gguf"
            ),
            AiModelInfo(
                id = "deepseek-r1-qwen-1.5b-int4",
                name = "DeepSeek R1 Distill 1.5B Flash",
                developer = "DeepSeek AI",
                sizeBytes = 1_100_000_000L,
                sizeFormatted = "1.10 GB",
                ramRequiredMb = 1400,
                parameterCount = "1.78 Billion",
                quantization = "INT4 (q4_k_m)",
                targetTokensPerSec = 18.5,
                description = "DeepSeek R1 distilled reasoning model. Features step-by-step thinking chain output and exceptional mathematical proof solving.",
                tags = listOf("DeepSeek R1", "Reasoning", "Chain-of-Thought", "Flash"),
                category = ModelCategory.BALANCED,
                isRecommended = true,
                downloadUrl = "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf"
            ),
            AiModelInfo(
                id = "minicpm-v-2.6-int4",
                name = "MiniCPM-V 2.6 Multimodal",
                developer = "OpenBMB / Tsinghua",
                sizeBytes = 1_850_000_000L,
                sizeFormatted = "1.85 GB",
                ramRequiredMb = 2400,
                parameterCount = "3.2 Billion",
                quantization = "INT4 (q4_k_m)",
                targetTokensPerSec = 13.0,
                description = "Edge vision-language AI for mobile devices. Supports document understanding, image captioning, and visual Q&A.",
                tags = listOf("OpenBMB", "MiniCPM-V", "Multimodal", "Vision"),
                category = ModelCategory.HIGH_QUALITY,
                isRecommended = false,
                downloadUrl = "https://huggingface.co/openbmb/MiniCPM-V-2_6-gguf/resolve/main/MiniCPM-V-2_6-Q4_K_M.gguf"
            ),
            AiModelInfo(
                id = "phi-3-mini-3.8b-int4",
                name = "Phi-3 Mini 3.8B",
                developer = "Microsoft",
                sizeBytes = 2_250_000_000L,
                sizeFormatted = "2.25 GB",
                ramRequiredMb = 3200,
                parameterCount = "3.8 Billion",
                quantization = "INT4 (q4_k_m)",
                targetTokensPerSec = 9.8,
                description = "Microsoft's highly capable textbook-quality reasoning engine. Requires modern octa-core CPU and at least 6GB phone RAM.",
                tags = listOf("Microsoft", "High Quality", "Complex Logic"),
                category = ModelCategory.HIGH_QUALITY,
                isRecommended = false,
                downloadUrl = "https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf"
            )
        )
    }
}
